#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := test_INA219

ifndef ESP32_SENSOR_PATH
$(error ESP32_SENSOR_PATH variable is not set to a valid directory.)
endif

ifndef IDF_PATH
$(error IDF_PATH variable is not set to a valid directory.)
endif

include $(IDF_PATH)/make/project.mk
